/* Event impact analysis v1: read-only nearby/special event effect foundation for future AI use. */
(function(root){
  'use strict';
  if(root.InsightEventImpactAnalysis)return;
  var VERSION=1,DEFAULT_WINDOW_WEEKS=4,MIN_CONTROL_PER_WEEKDAY=2;
  var KPI_SPECS={salesYen:{label:'売上',thresholdPct:5},customers:{label:'客数',thresholdPct:5},customerUnitPrice:{label:'客単価',thresholdPct:5},items:{label:'買上点数',thresholdPct:5}};
  var HOURLY_THRESHOLD_PCT=10,HOURLY_MIN_ABS_CHANGE=3;
  function finite(value){var n=Number(value);return Number.isFinite(n)?n:null;}
  function object(value){return !!value&&typeof value==='object'&&!Array.isArray(value);}
  function pad(value){return String(value).padStart(2,'0');}
  function parseIso(value){var m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(String(value||''));if(!m)return null;var d=new Date(0);d.setFullYear(Number(m[1]),Number(m[2])-1,Number(m[3]));d.setHours(12,0,0,0);return d.getFullYear()===Number(m[1])&&d.getMonth()===Number(m[2])-1&&d.getDate()===Number(m[3])?d:null;}
  function iso(date){return date.getFullYear()+'-'+pad(date.getMonth()+1)+'-'+pad(date.getDate());}
  function shift(value,days){var d=parseIso(value);if(!d)return null;d.setDate(d.getDate()+Number(days||0));return iso(d);}
  function eachDate(start,end){var out=[],cursor=start,guard=0;while(cursor&&cursor<=end&&guard<3700){out.push(cursor);cursor=shift(cursor,1);guard++;}return out;}
  function weekday(value){var d=parseIso(value);return d?d.getDay():null;}
  function environment(overrides){overrides=overrides||{};var all=overrides.allStores;if(all===undefined){try{if(typeof allStores!=='undefined')all=allStores;}catch(_){}}if(all===undefined)all=root.allStores;return {allStores:all,analysis:overrides.AnalysisContext||root.InsightAnalysisContext,events:overrides.Events||root.InsightEvents,hourly:overrides.HourlyCustomers||root.InsightHourlyCustomers};}
  function findEvent(env,storeId,eventId){var store=env.allStores&&env.allStores.stores&&env.allStores.stores[storeId],items=store&&Array.isArray(store.events)?store.events:[],event=items.find(function(item){return item&&item.id===eventId;});if(!event||['nearby','special'].indexOf(event.type)<0)throw new Error('対象イベント・催事を取得できません。');if(!parseIso(event.startDate)||!parseIso(event.endDate)||event.startDate>event.endDate)throw new Error('イベント開催期間が不正です。');return JSON.parse(JSON.stringify(event));}
  function eventSummary(env,event){try{return env.events&&typeof env.events.summary==='function'?env.events.summary(event.snapshot):String(event.snapshot&&event.snapshot.title||'');}catch(_){return String(event.snapshot&&event.snapshot.title||'');}}
  function inputDay(day){return !!(day&&day.metrics&&Number(day.metrics.inputDays)>0);}
  function eventIds(day){return day&&day.conditions&&Array.isArray(day.conditions.eventIds)?day.conditions.eventIds:[];}
  function normalControlDay(day,targetWeekdays){return inputDay(day)&&day.conditions&&!day.conditions.holiday&&eventIds(day).length===0&&targetWeekdays.has(day.conditions.weekday);}
  function aggregateKpis(days){days=(days||[]).filter(inputDay);function values(key){return days.map(function(day){return finite(day.metrics&&day.metrics[key]);}).filter(function(v){return v!==null;});}function mean(list){return list.length?list.reduce(function(s,v){return s+v;},0)/list.length:null;}var sales=values('salesYen'),customers=values('customers'),items=values('items'),salesSum=sales.reduce(function(s,v){return s+v;},0),customerSum=customers.reduce(function(s,v){return s+v;},0);return {sampleCount:days.length,salesYen:mean(sales),customers:mean(customers),customerUnitPrice:sales.length&&customers.length&&customerSum>0?salesSum/customerSum:null,items:mean(items)};}
  function weekdayWeights(days){var weights=[0,0,0,0,0,0,0];(days||[]).filter(inputDay).forEach(function(day){if(day.conditions&&Number.isInteger(day.conditions.weekday))weights[day.conditions.weekday]++;});return weights;}
  function emptyKpis(){return {sampleCount:0,salesYen:null,customers:null,customerUnitPrice:null,items:null};}
  function weightedBaseline(days,weights){var groups={},totalWeight=weights.reduce(function(s,v){return s+v;},0);if(!totalWeight)return {available:false,sampleCount:days.length,groups:groups,metrics:emptyKpis()};var weighted={salesYen:0,customers:0,items:0},ok={salesYen:true,customers:true,items:true};for(var i=0;i<7;i++){if(!weights[i])continue;var group=days.filter(function(day){return day.conditions&&day.conditions.weekday===i;}),metrics=aggregateKpis(group);groups[i]={sampleCount:group.length,weight:weights[i],metrics:metrics};if(group.length<MIN_CONTROL_PER_WEEKDAY)return {available:false,sampleCount:days.length,requiredWeekday:i,groups:groups,metrics:emptyKpis()};['salesYen','customers','items'].forEach(function(key){if(metrics[key]===null){ok[key]=false;return;}weighted[key]+=metrics[key]*weights[i];});}var metrics={sampleCount:days.length,salesYen:ok.salesYen?weighted.salesYen/totalWeight:null,customers:ok.customers?weighted.customers/totalWeight:null,customerUnitPrice:ok.salesYen&&ok.customers&&weighted.customers>0?weighted.salesYen/weighted.customers:null,items:ok.items?weighted.items/totalWeight:null};return {available:true,sampleCount:days.length,requiredWeekday:null,groups:groups,metrics:metrics};}
  function compare(value,baseline,spec){if(value===null||baseline===null)return {available:false,direction:'unknown',changePct:null};if(baseline===0)return value===0?{available:true,direction:'flat',changePct:0}:{available:false,direction:'unknown',changePct:null};var pct=(value-baseline)/Math.abs(baseline)*100,limit=spec.thresholdPct||0;return {available:true,direction:Math.abs(pct)<=limit?'flat':pct>0?'up':'down',changePct:pct};}
  function compareKpis(eventMetrics,baselineMetrics,available){var out={};Object.keys(KPI_SPECS).forEach(function(key){var c=available?compare(eventMetrics[key],baselineMetrics[key],KPI_SPECS[key]):{available:false,direction:'unknown',changePct:null};out[key]={key:key,label:KPI_SPECS[key].label,event:eventMetrics[key],baseline:baselineMetrics[key],comparison:c};});return out;}
  function hourlyStatus(env,storeId,date){if(!env.hourly||typeof env.hourly.status!=='function')return null;try{return env.hourly.status(env.allStores,storeId,date);}catch(_){return null;}}
  function completeHourlyDays(env,storeId,dates){return dates.map(function(date){var s=hourlyStatus(env,storeId,date);return s&&s.complete?{date:date,weekday:weekday(date),hours:s.hours.slice()}:null;}).filter(Boolean);}
  function hourlyAverage(days){if(!days.length)return null;var out=Array(24).fill(0);days.forEach(function(day){for(var h=0;h<24;h++)out[h]+=Number(day.hours[h]||0);});return out.map(function(total){return total/days.length;});}
  function weightedHourlyBaseline(days,weights){var totalWeight=weights.reduce(function(s,v){return s+v;},0),groups={},profile=Array(24).fill(0);if(!totalWeight)return {available:false,sampleCount:days.length,groups:groups,profile:null};for(var i=0;i<7;i++){if(!weights[i])continue;var group=days.filter(function(day){return day.weekday===i;}),avg=hourlyAverage(group);groups[i]={sampleCount:group.length,weight:weights[i],profile:avg};if(group.length<MIN_CONTROL_PER_WEEKDAY||!avg)return {available:false,sampleCount:days.length,requiredWeekday:i,groups:groups,profile:null};for(var h=0;h<24;h++)profile[h]+=avg[h]*weights[i];}return {available:true,sampleCount:days.length,requiredWeekday:null,groups:groups,profile:profile.map(function(v){return v/totalWeight;})};}
  function hourlyDirection(eventValue,baselineValue){if(eventValue===null||baselineValue===null)return {direction:'unknown',difference:null,changePct:null};var diff=eventValue-baselineValue;if(Math.abs(diff)<HOURLY_MIN_ABS_CHANGE)return {direction:'flat',difference:diff,changePct:baselineValue?diff/baselineValue*100:null};if(baselineValue===0)return {direction:diff>0?'up':'down',difference:diff,changePct:null};var pct=diff/Math.abs(baselineValue)*100;return {direction:Math.abs(pct)<HOURLY_THRESHOLD_PCT?'flat':pct>0?'up':'down',difference:diff,changePct:pct};}
  function peak(profile){if(!Array.isArray(profile)||profile.length!==24)return null;var max=Math.max.apply(null,profile),hour=profile.indexOf(max);return {hour:hour,value:max};}
  function hourlyComparison(eventProfile,baselineProfile){if(!eventProfile||!baselineProfile)return [];return eventProfile.map(function(value,hour){var baseline=baselineProfile[hour],d=hourlyDirection(value,baseline);return {hour:hour,eventAverage:value,baselineAverage:baseline,difference:d.difference,changePct:d.changePct,direction:d.direction};});}
  function analyzeOccurrence(options,overrides){options=options||{};var env=environment(overrides);if(!object(env.allStores)||!object(env.allStores.stores))throw new Error('店舗データを取得できません。');if(!env.analysis||typeof env.analysis.buildRange!=='function')throw new Error('分析コンテキストを利用できません。');if(!env.events)throw new Error('イベント機能を利用できません。');if(!env.hourly)throw new Error('時間帯別客数機能を利用できません。');var storeId=options.storeId||env.allStores.current,store=env.allStores.stores[storeId];if(!object(store))throw new Error('対象店舗を取得できません。');var event=findEvent(env,storeId,options.eventId),windowWeeks=Number(options.windowWeeks||DEFAULT_WINDOW_WEEKS);if(!Number.isInteger(windowWeeks)||windowWeeks<1||windowWeeks>12)throw new Error('イベント比較期間が不正です。');var beforeStart=shift(event.startDate,-7*windowWeeks),afterEnd=shift(event.endDate,7*windowWeeks),context=env.analysis.buildRange(beforeStart,afterEnd,storeId,overrides),daily=context&&Array.isArray(context.daily)?context.daily:[],eventDateSet=new Set(eachDate(event.startDate,event.endDate)),eventDays=daily.filter(function(day){return eventDateSet.has(day.date)&&inputDay(day);}),weights=weekdayWeights(eventDays),targetWeekdays=new Set(weights.map(function(weight,index){return weight?index:null;}).filter(function(v){return v!==null;})),controlDays=daily.filter(function(day){return !eventDateSet.has(day.date)&&normalControlDay(day,targetWeekdays);}),baseline=weightedBaseline(controlDays,weights),eventMetrics=aggregateKpis(eventDays);
    var eventHourly=completeHourlyDays(env,storeId,eachDate(event.startDate,event.endDate)),hourlyWeights=[0,0,0,0,0,0,0];eventHourly.forEach(function(day){hourlyWeights[day.weekday]++;});var hourlyWeekdays=new Set(hourlyWeights.map(function(weight,index){return weight?index:null;}).filter(function(v){return v!==null;})),controlHourlyDates=controlDays.filter(function(day){return hourlyWeekdays.has(day.conditions.weekday);}).map(function(day){return day.date;}),controlHourly=completeHourlyDays(env,storeId,controlHourlyDates),eventProfile=hourlyAverage(eventHourly),hourlyBaseline=weightedHourlyBaseline(controlHourly,hourlyWeights),hourlyProfile=hourlyComparison(eventProfile,hourlyBaseline.profile);
    var otherEventDays=eventDays.filter(function(day){return eventIds(day).some(function(id){return id!==event.id;});}),holidayDays=eventDays.filter(function(day){return !!(day.conditions&&day.conditions.holiday);}),weather=eventDays.map(function(day){return {date:day.date,weather:day.conditions&&day.conditions.weather||null,tempMaxC:day.conditions?finite(day.conditions.tempMaxC):null,tempMinC:day.conditions?finite(day.conditions.tempMinC):null};});
    return {version:VERSION,store:{id:storeId,name:String(store.name||storeId)},event:{id:event.id,type:event.type,kind:event.type==='special'?'special':'nearby',title:String(event.snapshot&&event.snapshot.title||''),location:event.type==='nearby'?String(event.snapshot&&event.snapshot.location||''):'',summary:eventSummary(env,event),startDate:event.startDate,endDate:event.endDate},window:{startDate:beforeStart,endDate:afterEnd,weeksEachSide:windowWeeks},policy:{weekdayMatched:true,controlDayDefinition:'sameWeekdayNoEventNoHoliday',minimumControlPerWeekday:MIN_CONTROL_PER_WEEKDAY,hourlyRequiresComplete24Hours:true},samples:{eventDays:eventDays.length,controlDays:controlDays.length,weekdayWeights:weights,baselineAvailable:baseline.available,eventHourlyDays:eventHourly.length,controlHourlyDays:controlHourly.length,hourlyBaselineAvailable:hourlyBaseline.available},kpi:{event:eventMetrics,baseline:baseline.metrics,metrics:compareKpis(eventMetrics,baseline.metrics,baseline.available)},hourly:{available:!!eventProfile&&hourlyBaseline.available,eventProfile:eventProfile,baselineProfile:hourlyBaseline.profile,profile:hourlyProfile,eventPeak:peak(eventProfile),baselinePeak:peak(hourlyBaseline.profile),increasedHours:hourlyProfile.filter(function(item){return item.direction==='up';}).map(function(item){return item.hour;}),decreasedHours:hourlyProfile.filter(function(item){return item.direction==='down';}).map(function(item){return item.hour;})},confounders:{holidayEventDays:holidayDays.map(function(day){return day.date;}),otherEventDays:otherEventDays.map(function(day){return {date:day.date,eventIds:eventIds(day).filter(function(id){return id!==event.id;})};}),weather:weather},source:{savedOnly:true,readOnly:true,externalTransmission:false}};
  }
  var model={VERSION:VERSION,DEFAULT_WINDOW_WEEKS:DEFAULT_WINDOW_WEEKS,MIN_CONTROL_PER_WEEKDAY:MIN_CONTROL_PER_WEEKDAY,KPI_SPECS:KPI_SPECS,analyzeOccurrence:analyzeOccurrence,aggregateKpis:aggregateKpis,weightedBaseline:weightedBaseline,completeHourlyDays:completeHourlyDays,weightedHourlyBaseline:weightedHourlyBaseline,hourlyDirection:hourlyDirection,hourlyComparison:hourlyComparison,peak:peak};
  if(typeof module!=='undefined'&&module.exports)module.exports=model;
  root.InsightEventImpactAnalysis=model;
})(typeof window!=='undefined'?window:globalThis);
