const test=require('node:test');
const assert=require('node:assert/strict');
const impact=require('../insight_event_impact_v1.js');
const events=require('../insight_events_v1.js');
const hourly=require('../insight_hourly_customers_v1.js');
function iso(date){return date.getFullYear()+'-'+String(date.getMonth()+1).padStart(2,'0')+'-'+String(date.getDate()).padStart(2,'0');}
function row(date,sales,customers,items,options={}){const d=new Date(date+'T12:00:00');return {date,metrics:{salesYen:sales,customers,customerUnitPrice:customers?sales/customers:null,items,inputDays:1},conditions:{weekday:d.getDay(),weekdayLabel:['日','月','火','水','木','金','土'][d.getDay()],holiday:!!options.holiday,weather:options.weather||'晴',tempMaxC:options.tempMaxC||25,tempMinC:options.tempMinC||15,eventIds:options.eventIds||[]}};}
function hours(base,peakHour,extra){return Array.from({length:24},(_,h)=>base+(h===peakHour?extra:0));}
function fixture(){const event={id:'nearby_oct',type:'nearby',scope:'store',startDate:'2026-10-10',endDate:'2026-10-11',snapshot:{version:1,title:'秋まつり',note:'',location:'文化フォーラム'}};const all={current:'storeA',eventManagement:{version:1,presets:[],events:[]},stores:{storeA:{name:'A店',events:[event],hourlyCustomers:{}}}};const rows=[],start=new Date('2026-09-12T12:00:00'),end=new Date('2026-11-08T12:00:00');for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){const date=iso(d),wd=d.getDay(),isEvent=date>='2026-10-10'&&date<='2026-10-11';let sales=100000,customers=100,items=150;if(wd===6){sales=120000;customers=110;items=165;}if(wd===0){sales=130000;customers=115;items=175;}if(isEvent){sales*=1.25;customers*=1.3;items*=1.2;}rows.push(row(date,sales,customers,items,{eventIds:isEvent?['nearby_oct']:[],weather:isEvent?'曇':'晴'}));if(wd===6||wd===0)all.stores.storeA.hourlyCustomers[date]=isEvent?hours(5,18,30):hours(5,16,15);}rows.find(x=>x.date==='2026-09-19').conditions.eventIds=['other_event'];rows.find(x=>x.date==='2026-10-25').conditions.holiday=true;return {all,event,rows};}
function deps(f){return {allStores:f.all,AnalysisContext:{buildRange(start,end){return {daily:f.rows.filter(x=>x.date>=start&&x.date<=end)};}},Events:events,HourlyCustomers:hourly};}
test('近隣イベントを同曜日通常日と比較し売上・客数の影響を算出する',()=>{const f=fixture(),r=impact.analyzeOccurrence({eventId:'nearby_oct',storeId:'storeA',windowWeeks:4},deps(f));assert.equal(r.event.kind,'nearby');assert.equal(r.event.title,'秋まつり');assert.equal(r.event.location,'文化フォーラム');assert.deepEqual(r.samples.weekdayWeights,[1,0,0,0,0,0,1]);assert.equal(r.samples.baselineAvailable,true);assert.equal(r.kpi.metrics.salesYen.comparison.direction,'up');assert.equal(r.kpi.metrics.customers.comparison.direction,'up');assert.ok(r.kpi.event.salesYen>r.kpi.baseline.salesYen);});
test('祝日・別イベント日は通常日基準から除外する',()=>{const f=fixture(),r=impact.analyzeOccurrence({eventId:'nearby_oct',storeId:'storeA',windowWeeks:4},deps(f));assert.ok(r.samples.controlDays>=4);assert.equal(r.policy.controlDayDefinition,'sameWeekdayNoEventNoHoliday');});
test('完全入力済み24時間データだけで時間帯別のイベント影響を比較する',()=>{const f=fixture(),r=impact.analyzeOccurrence({eventId:'nearby_oct',storeId:'storeA',windowWeeks:4},deps(f));assert.equal(r.hourly.available,true);assert.equal(r.samples.eventHourlyDays,2);assert.ok(r.samples.controlHourlyDays>=4);assert.equal(r.hourly.eventPeak.hour,18);assert.equal(r.hourly.baselinePeak.hour,16);assert.ok(r.hourly.increasedHours.includes(18));const h18=r.hourly.profile.find(item=>item.hour===18);assert.equal(h18.direction,'up');assert.ok(h18.eventAverage>h18.baselineAverage);});
test('時間帯別客数の一部入力日は比較対象に含めない',()=>{const f=fixture();f.all.stores.storeA.hourlyCustomers['2026-10-10'][3]=null;const r=impact.analyzeOccurrence({eventId:'nearby_oct',storeId:'storeA',windowWeeks:4},deps(f));assert.equal(r.samples.eventHourlyDays,1);assert.equal(r.hourly.available,true);});
test('同曜日通常日が不足する場合はKPI影響を断定しない',()=>{const f=fixture(),r=impact.analyzeOccurrence({eventId:'nearby_oct',storeId:'storeA',windowWeeks:1},deps(f));assert.equal(r.samples.baselineAvailable,false);assert.equal(r.kpi.metrics.salesYen.comparison.available,false);assert.equal(r.kpi.metrics.salesYen.comparison.direction,'unknown');});
test('開催日に祝日や別イベントが重なった場合は交絡要因として保持する',()=>{const f=fixture();f.rows.find(x=>x.date==='2026-10-10').conditions.holiday=true;f.rows.find(x=>x.date==='2026-10-11').conditions.eventIds.push('special_other');const r=impact.analyzeOccurrence({eventId:'nearby_oct',storeId:'storeA',windowWeeks:4},deps(f));assert.deepEqual(r.confounders.holidayEventDays,['2026-10-10']);assert.deepEqual(r.confounders.otherEventDays,[{date:'2026-10-11',eventIds:['special_other']}]);assert.equal(r.confounders.weather.length,2);});
test('催事も同じ分析基盤で処理し保存データを書き換えない',()=>{const f=fixture();f.all.stores.storeA.events.push({id:'special_oct',type:'special',scope:'store',startDate:'2026-10-10',endDate:'2026-10-11',snapshot:{version:1,title:'店頭催事',note:''}});f.rows.filter(x=>x.date>='2026-10-10'&&x.date<='2026-10-11').forEach(x=>x.conditions.eventIds.push('special_oct'));const before=JSON.stringify(f.all);const r=impact.analyzeOccurrence({eventId:'special_oct',storeId:'storeA',windowWeeks:4},deps(f));assert.equal(r.event.kind,'special');assert.equal(r.event.location,'');assert.equal(JSON.stringify(f.all),before);assert.equal(r.source.externalTransmission,false);});
test('セール等はイベント影響分析の対象外',()=>{const f=fixture();f.all.stores.storeA.events.push({id:'staff1',type:'staff',scope:'store',startDate:'2026-10-10',endDate:'2026-10-10',snapshot:{version:1,title:'応援',note:''}});assert.throws(()=>impact.analyzeOccurrence({eventId:'staff1',storeId:'storeA'},deps(f)),/対象イベント・催事/);});
